### PR TITLE
bump compileSdkVersion to 28

### PR DESCRIPTION
**Pull request by ingvardm**
#24  Summary
fixes issue #43 

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ❌     |
| Android |    ✅     |

## Checklist

- [X] I have tested this on a device and a simulator
- [ ] I added the documentation in `README.md`
- [ ] I mentioned this change in `CHANGELOG.md`
- [ ] I updated the typed files (TS and Flow)
- [ ] I added a sample use of the API in the example project (`example/App.js`)

### CODE REVIEW

**Comment by oleksandr-dziuban** [comment]
Can this be merged soon? And same we need for react-native-community/progress-view for iOS

**Comment by HazemMhiri** [comment]
I hope this gets merged soon as the library is unusable with RN 0.62 in its current state.

**Comment by oleksandr-dziuban** [comment]
@Naturalclar Could you please bump npm package?
And could you please update the ios progress-view library with the same fix? Thanks a lot!

**Comment by Naturalclar** [comment]
@oleksandr-dziuban I've bumped both progress-view and progress-bar with the fix :+1: Both of them should have the fix applied in version `1.0.3`

**Pull request merged**
